Catkin-ProjectName: dynamic_reconfigure
Version: 0.0.0
Description: 
Author: 
Maintainer: 
Homepage: 

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

Architecture: any
Depends: ros_comm, roscpp_core, std_msgs
